name: CI MLflow Training 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-train-docker:
    runs-on: ubuntu-latest

    env:
      CSV_URL: weather_dataset_preprocessing.csv
      MLFLOW_TRACKING_URI: file:./mlruns
      DOCKER_USER_NAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model with MLflow
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    - name: Verify MLflow artifacts
      run: |
        cd MLProject
        find mlruns -maxdepth 4 -type d

    - name: Get MLflow run_id
      run: |
        cd MLProject
        RUN_ID=$(ls mlruns/0 | head -n 1)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Using RUN_ID=$RUN_ID"
    
    - name: Debug MLflow Artifacts
      run: |
        cd MLProject
        find mlruns -type d
    
    - name: Build Docker image from MLflow model
      run: |
        cd MLProject
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model" \
          --name cc

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag cc $DOCKER_USER_NAME/cc:latest
        docker push $DOCKER_USER_NAME/cc:latest
