name: CI for Modelling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

env:
  CSV_URL: "weather_dataset_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: GitHub

    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      EMAIL: ${{ secrets.EMAIL }}
      DOCKER_USER_NAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git Identity
      run: |
        git config --global user.name "$USER_NAME"
        git config --global user.email "$EMAIL"

    - name: Set up Python 3.12.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set MLflow Tracking URI
      run: |
        echo "MLFLOW_TRACKING_URI=sqlite:///mlflow.db" >> $GITHUB_ENV

    - name: Run MLflow Project
      run: |
        mlflow run . --env-manager=local

    - name: Setup Git LFS
      run: |
        git lfs install
        git lfs track "mlruns/**"
        git add .gitattributes
        git commit -m "Track mlruns with Git LFS" || true

    - name: Commit MLflow Artifacts
      run: |
        if [ -d "mlruns" ]; then
          git add mlruns/
        fi
        if git diff --cached --quiet; then
          echo "No MLflow changes"
        else
          git commit -m "Save MLflow artifacts"
          git push origin main
        fi

    - name: Get Latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    - name: Build Docker Model
      run: |
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model" \
          --name cc

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag cc $DOCKER_USER_NAME/cc:latest

    - name: Push Docker Image
      run: |
        docker push $DOCKER_USER_NAME/cc:latest
